"""chat_history workspace_id and conversation_title

Revision ID: 16c76796466c
Revises: af9534adb775
Create Date: 2026-06-22 18:40:28.510876
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '16c76796466c'
down_revision: Union[str, None] = 'af9534adb775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('chat_history', sa.Column('conversation_title', sa.String(length=64), nullable=True))
    op.create_index('ix_chat_history_user_ws_created', 'chat_history', ['user_id', 'workspace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_history_user_ws_created', table_name='chat_history')
    op.drop_column('chat_history', 'conversation_title')
    op.drop_column('chat_history', 'workspace_id')
    # ### end Alembic commands ###
