"""add meetings table

Revision ID: 9f0caa3a724c
Revises: 1f6b768891a9
Create Date: 2026-06-26 11:13:28.589729
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '9f0caa3a724c'
down_revision: Union[str, None] = '1f6b768891a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('dimension_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_dimension_id'), 'meetings', ['dimension_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_dimension_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
