"""add_user_llm_config

Revision ID: a1f320c49285
Revises: 9d84d66c2f9b
Create Date: 2026-06-22 14:17:12.424884
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a1f320c49285'
down_revision: Union[str, None] = '9d84d66c2f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('llm_api_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('llm_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'llm_model')
    op.drop_column('users', 'llm_api_key')
    # ### end Alembic commands ###
