"""add dimension and dimension_id columns to project_reports

Revision ID: f4f8b7372aba
Revises: c3d4e5f6a7b8
Create Date: 2026-07-13 05:56:15.188214
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f4f8b7372aba'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add nullable first so we can backfill existing rows
    op.add_column('project_reports', sa.Column('dimension', sa.String(length=20), nullable=True))
    op.add_column('project_reports', sa.Column('dimension_id', sa.String(length=36), nullable=True))

    # Backfill: existing rows use their workspace_id as both dimension and dimension_id
    op.execute(
        "UPDATE project_reports SET dimension = 'PROJECT', dimension_id = workspace_id"
    )

    # Now make NOT NULL and drop old column
    op.alter_column('project_reports', 'dimension', existing_type=sa.String(20), nullable=False)
    op.alter_column('project_reports', 'dimension_id', existing_type=sa.String(36), nullable=False)

    op.drop_index(op.f('ix_project_reports_workspace_id'), table_name='project_reports')
    op.create_index(op.f('ix_project_reports_dimension_id'), 'project_reports', ['dimension_id'], unique=False)
    op.drop_constraint(op.f('project_reports_workspace_id_fkey'), 'project_reports', type_='foreignkey')
    op.drop_column('project_reports', 'workspace_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_reports', sa.Column('workspace_id', sa.VARCHAR(length=36), nullable=False, server_default=''))
    op.create_foreign_key(op.f('project_reports_workspace_id_fkey'), 'project_reports', 'workspaces', ['workspace_id'], ['id'])
    op.drop_index(op.f('ix_project_reports_dimension_id'), table_name='project_reports')
    op.create_index(op.f('ix_project_reports_workspace_id'), 'project_reports', ['workspace_id'], unique=False)
    op.drop_column('project_reports', 'dimension_id')
    op.drop_column('project_reports', 'dimension')
    # ### end Alembic commands ###
